"LEADER MAPPINGS
nnoremap <Leader>t :let $VIM_DIR=expand('%:p:h')<CR>:terminal<CR>cd $VIM_DIR<CR>
"nnoremap <leader>h :set hlsearch!<cr> 
nnoremap <leader>vv :e $MYVIMRC<CR>
nnoremap <leader>vt :e ~/.tmux.conf<CR>
nnoremap <leader>vr :source $MYVIMRC<CR>
nnoremap <leader>nh :nohlsearch<cr> 
"nnoremap <leader>nn :set nu! rnu!<CR>
nnoremap <leader>nn :set nu!<CR>

"NETRW
let g:netrw_banner=0
"let g:netrw_browse_split=4  " open in prior window
"let g:netrw_altv=1          " open splits to the right
"let g:netrw_liststyle=3     " tree view
"let g:netrw_list_hide=netrw_gitignore#Hide()
"let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

"MY MAPPINGS
set nocompatible
syntax enable
filetype plugin on
set path+=**
"set nu rnu
set nu
set wildmenu
set wildmode=longest:list,full

set tabstop=4
set shiftwidth=0
set expandtab

"set colorcolumn=78
"hi ColorColumn ctermbg=grey guibg=grey

""left hand grid
"inoremap ä 0
"inoremap å ^ 
"inoremap é (
"inoremap ë )
"inoremap á {
"inoremap ß }
"inoremap ð %
""inoremap f
"inoremap æ $
"inoremap œ $
"inoremap © [
"inoremap ® ]
"
""2 middle columns
"inoremap þ $
""inoremap g
""inoremap b
"inoremap ü `
""inoremap h
"inoremap ñ ~ 
"
""right hand grid
"inoremap ú 7
"inoremap ˙ 3
"
"
""normal mode
"nnoremap ä 0
"nnoremap å ^ 
"nnoremap é (
"nnoremap ë )
"nnoremap á {
"nnoremap ß }
"nnoremap ð %
""ninoremap f
"nnoremap æ $
"nnoremap œ $
"nnoremap © [
"nnoremap ® ]
